version: '2.2'
networks: {}
volumes:
  resin-data: {}
services:
  jellyfin:
    image: linuxserver/jellyfin:10.7.7
    devices:
      - /dev/vchiq:/dev/vchiq ##HWA Chip
    container_name: jellyfin
    network_mode: host
    privileged: true
    restart: always
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris 
      UMASK_SET: "022"
    volumes:
      - 'resin-data:/data'
      - /data/jellyfin:/config
      - /media:/media
      - /dev/shm:/config/data/transcoding-temp/transcodes
      - /opt/vc/lib:/opt/vc/lib   ## OpenMax Libraries
    labels:
      io.balena.features.kernel-modules: '1'
      io.balena.features.firmware: '1'
      io.balena.features.dbus: '1'
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-api: '1'