version: '2.1'
networks: {}
volumes:
  vol-config: {}
  vol-cache: {}
services:
  jellyfin:
    image: 'linuxserver/jellyfin:10.7.7'
    devices:
      - '/dev/vchiq:/dev/vchiq'
    container_name: jellyfin
    network_mode: host
    privileged: true
    restart: always
    environment:
      UDEV: 'on'
      PUID: '1000'
      PGID: '1000'
      TZ: Europe/Paris
      UMASK_SET: '022'
    volumes:
      - 'vol-config:/config'
      - 'vol-cache:/cache'
    labels:
      io.balena.features.external-storage: '1'
      io.balena.features.kernel-modules: '1'
      io.balena.features.firmware: '1'
      io.balena.features.dbus: '1'
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-api: '1'
